title: Jacob Laughlin's Site
author: Jacob L. Laughlin
description: Welcome to my site! Here you can find out about me, my projects, and my work.

theme: minima

header_pages:
  - cv.md
  - project_index.md

